version: '3'
services:
  stlreader:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

#  nginx:
#    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - meu-app-go